apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingres-cilist
spec:
  rules:
  - host: cilist.arifamru.my.id
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: cilistfrontend
            port:
              name: http