apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cilistbackend.fullname" . }}-configmap
  labels:
    {{- include "cilistbackend.labels" . | nindent 4 }}
data:
  {{ toYaml .Values.config | nindent 2 }} 